### ISSUE TITLE
Conflicting js dependency versions on aggregated pages

### ISSUE THREAD

**Issue by dschulten** [gustafnk/microservice-websites#27]
What is a good practice to ensure that SPAs from several teams do not use conflicting js library and framework versions? Which are the tradeoffs to make?

Independently developed SPAs rarely use the same version of anything. Three apps from three teams on one page will almost certainly run three different versions of e.g. bootstrap, jquery and some mvc framework, not to mention plugins etc.

Currently the section "local scripts" focuses on load optimization. Do you assume implicitly that the teams coordinate shared versions of libraries, frameworks and plugins and update at a common pace?

**Comment by gustafnk** [comment]
I think you hit the nail on the head here, by focusing on this problem :) This is one of the reasons why you might not want to build microservice websites with an SPA approach and why I wanted to write this article.

For the CSS, I'd recommend the approach described in https://gustafnk.github.io/microservice-websites/#scaling-web-design , i.e. a styleguide (global CSS) used by all services.

For the JS, I'd go for progressively enhanced components in the styleguide as well (global JS) and in the cases where you really need service specific scripts, I'd develop them without any dependencies (which could be quite hard, so I'd avoid local JS as much as possible).

You could of course put jQuery in the shared JS as well, but then you'd get coordination costs and possible friction (i.e. some teams might have other business priorities than upgrading to a version of jQuery that another team needs for a feature).

Not sure if this makes sense for you... What do you think?

**Comment by dschulten** [comment]
A more recent alternative are no-framework frameworks like svelte.js.

**Comment by gustafnk** [comment]
Thanks for the tip :) I'll look into it. However, do you know if Svelte if version-less? Otherwise, upgrades anyway need to be coordinated between teams, right?

**Comment by dschulten** [comment]
The result of a svelte project build is *pure* html+javascript+css without any dependency on svelte.js. The browser does not pull in the svelte framework in any version.
